<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NARENDRA" ignored="0" name="personal loan" tests="8" failures="1" timestamp="2020-07-13T17:28:51 IST" time="0.177" errors="0">
  <testcase name="FirstTest" time="0.017" classname="test.Day1"/>
  <testcase name="SecondTest" time="0.012" classname="test.Day1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.Day1.SecondTest(Day1.java:19)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- SecondTest -->
  <testcase name="Login" time="0.006" classname="test.Day2"/>
  <testcase name="Login" time="0.007" classname="test.Day2"/>
  <testcase name="Login" time="0.002" classname="test.Day2"/>
  <testcase name="thirdTest" time="0.004" classname="test.Day2"/>
  <testcase name="MobileloginHomeLoan" time="0.003" classname="test.Day4"/>
  <testcase name="WebloginHomeLoan" time="0.007" classname="test.Day4"/>
</testsuite> <!-- personal loan -->
